const fields = [
    {
        type: 'api',
        name: 'api',
        value: '/forum',
    },
    {
        label: 'Category',
        name: 'category',
        type: 'select',
        defaultValue: 'select',
        value: '',
        options: [
            { label: 'Select', value: 'select', disabled: true },
            { label: 'Politics', value: 'politics' },
            { label: 'Tech', value: 'tech' },
            { label: 'Lifestyle', value: 'lifestyle' },
            { label: 'Health', value: 'health' },
            { label: 'Sports', value: 'sports' },
            { label: 'Entertainment', value: 'entertainment' },
            { label: 'Science', value: 'science' },
            { label: 'Travel', value: 'travel' },
            { label: 'Education', value: 'education' },
            { label: 'Business', value: 'business' },
            { label: 'Finance', value: 'finance' },
            { label: 'Food', value: 'food' },
            { label: 'Fashion', value: 'fashion' },
            { label: 'Automobile', value: 'automobile' },
            { label: 'Real Estate', value: 'real_estate' },
            { label: 'Parenting', value: 'parenting' },
            { label: 'Relationships', value: 'relationships' },
            { label: 'Religion', value: 'religion' },
            { label: 'Home', value: 'home' },
            { label: 'Garden', value: 'garden' },
            { label: 'Pets', value: 'pets' },
            { label: 'Environment', value: 'environment' },
            { label: 'Weather', value: 'weather' },
            { label: 'News', value: 'news' },
        ],
        required: true,
    },
    {
        label: 'Title',
        name: 'title',
        type: 'text',
        required: true,
        value: '',
        transformer: (value: string) => value.toLowerCase().replace(/[^\w]/g, '').substring(0, 25),
    },
    {
        label: 'Description',
        name: 'description',
        type: 'text',
        required: true,
        value: '',
    },
    {
        label: 'Content',
        name: 'content',
        type: 'text',
        required: true,
        value: '',
    },
];

export default fields;