export const errors: {[key: number]: string} = {
    404: 'Not found',
    403: 'Forbidden',
    401: 'Unauthorized',
    400: 'Bad request',
    500: 'Internal server error',
    503: 'Service unavailable',
    504: 'Gateway timeout',
    502: 'Bad gateway',
    429: 'Too many requests',
    408: 'Request timeout',
    413: 'Payload too large',
    415: 'Unsupported media type',
    406: 'Not acceptable',
    405: 'Method not allowed',
    501: 'Not implemented',
};